name: lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Packer Plugin Binaries
        run: packer init .

      - name: Validate Template
        env:
          PKR_VAR_project: dummy_value
        run: packer validate .